default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username:
  password:

development:
  <<: *default
  database: quiz_master_development

test:
  <<: *default
  database: quiz_master_test
